<?php
/** @var Grin\Module\Block\Checkout\CartWidget $block */
/** @var Magento\Framework\Escaper $escaper */
?>

<div id="block-cartid" class="block" data-mage-init='{"collapsible":{"openedState": "active", "saveState": true}}'>
    <div class="title" data-role="title" aria-controls="block-cartid" role="tab" aria-selected="false"
         aria-expanded="false">
        <strong id="block-cartid-heading" role="heading" aria-level="2">Cart ID</strong>
    </div>
    <div id="block-cart-widget"
         data-bind="scope:'block-cart-widget'"
         class="content"
         data-role="content"
         aria-labelledby="block-cardid-heading">
        <div class="block">
            <input id="cart-id"
                   disabled="disabled"
                   value="<?= $escaper->escapeHtml($block->getQuoteId()) ?>"
                   type="text"
                   style="background-color: #f5f5f5"/>
            <br>
            <button style="float: right; margin: 10px 0 20px 0;"
                    class="small right"
                    onclick="copyToClipboard()"><?= $escaper->escapeHtml(__('Copy')) ?></button>
            <script>
                function copyToClipboard() {
                    var dummy = document.createElement("textarea"),
                        id = document.getElementById('cart-id').value;
                    document.body.appendChild(dummy);
                    dummy.value = id;
                    dummy.select();
                    document.execCommand("copy");
                    document.body.removeChild(dummy);
                    alert(id + " copied to clipboard.");
                }
            </script>
        </div>
    </div>
</div>
